#!/bin/bash

PUBLIC_IP=0.0.0.0
PUBLIC_PORT=30000
LOCAL_IP=127.0.0.1
LOCAL_PORT=30001
PASSWORD=ThePasswordYouWant

docker run -d -p ${PUBLIC_PORT}:${PUBLIC_PORT} -p ${LOCAL_PORT}:${LOCAL_PORT} -e PUBLIC_IP=${PUBLIC_IP} -e PUBLIC_PORT=${PUBLIC_PORT} -e LOCAL_IP=${LOCAL_IP} -e LOCAL_PORT=${LOCAL_PORT} -e PASSWORD=${PASSWORD} aliciahan/npm-shadowsocks:v1


